GET http://localhost:8082
###
GET http://localhost:8082/currencies
###
GET http://localhost:8082/currencies/inr
###
GET http://localhost:8082/currencies?min_value=0.01 
###
GET http://localhost:8082/users
Authorization: LetMeIn
###
GET http://localhost:8082/users/06750d9e-84d3-4cd1-8f89-1710213d2576
###
GET http://localhost:8082/users/5
###
GET http://localhost:8082/users/search?gender=male
###
GET http://localhost:8082/users/search?age=49
###
GET http://localhost:8082/users/search?gender=female&age=49
###Authorization: LetMeIn
GET http://localhost:8082/users/search
Authorization: LetMeIn
###
GET http://localhost:8082/users/search?age=-5
###
GET http://localhost:8082/users/search?age=male
###
POST http://localhost:8082/blogs/new
Content-Type: application/json

{
    "title": "Japan",
    "content": "Japan seems like a great place to visit.I would love to go there someday.",
    "author": ["John Doe","Jane Doe"],
    "publishedAt": null
}
###
GET http://localhost:8082/blogs
###
POST http://localhost:8082/blogs/new
Content-Type: application/json

{
    "title": "Australia",
    "content": "Australia is a country and continent surrounded by the Indian and Pacifi oceans.Its major cities - Sydney, Brisbane, Melbourne, Perth, Adelaide - are coastal. Its capital , Canberra, is inland. The country is known for its Sydney Opera House, the Great Barrier Reef, a vast interior desert wilderness called the Outback, and unique animal species like kangaroos and duck-billed platypuses.",
    "author": ["James","Giovanni"],
    "publishedAt": null
}
###
POST http://localhost:8082/blogs/new
Content-Type: application/json

{
    "title": "India"
   
}
###
POST http://localhost:8082/blogs/new
Content-Type: application/json

{
    "content": "This is a blog post"
   
}
###
GET http://localhost:8082/blogs/67c8631bb507e2722155d480
###
PATCH  http://localhost:8082/blogs/67c8631bb507e2722155d480
Content-Type: application/json

{
    "content": "Australia is the land of Kangaroos",
    "author": ["Ponting","Lee"]
}
###
PATCH  http://localhost:8082/blogs/67c8631bb507e2722155d480
Content-Type: application/json

{
    "content": "Australia vs India",
    "author": ["Waugh","Starc"]
}
###
DELETE http://localhost:8082/blogs/67cd586eb430d40578773402
###
POST http://localhost:8082/blogs/new
Content-Type: application/json

{
    "title": "India",
    "content": "India is a country in South Asia",
    "author": [{
        "fullName": "Sachin Tendulkar",
        "email": "srt@gmail.com"
    },{
        "fullName": "Virot Kohli",
        "email": "king.kohli@gmail.com"
    }
    ]
}
###
POST http://localhost:8082/blogs/new
Content-Type: application/json

{
    "title": "Australia",
    "content": "Australia is a Ocean.",
    "author": [{
        "fullName": "Steve Smith",
        "email": "stevie@gmail.com"
    }
    ]
}
###
POST http://localhost:8082/blogs/new
Content-Type: application/json

{
    "title": "England",
    "content": "England is a country in Europe.",
    "author": [{
        "fullName": "Ben Stokes",
        "email": "ben"
    }
    ]
}
###
POST http://localhost:8082/blogs/new
Content-Type: application/json

{
    "title": "New Zealand",
    "content": "New Zealand is a country in the southwestern Pacific Ocean.",
    "author": [{
        "fullName": "Kane Williamson Kane Williamson Kane Williamson",
        "email": "kane@nz.com"
    }
    ]
}
###
POST http://localhost:8082/blogs/new
Content-Type: application/json

{
    "title": "New Zealand",
    "content": "New Zealand is a country in the southwestern Pacific Ocean.",
    "author": [{
        "fullName": "Kane Williamson",
        "email": "kane@nz.com"
    },
    {
        "fullName": "Ross Tailor",
        "email": "kane@nz.com"
    }
    ]
}
###
POST http://localhost:8082/blogs/new
Content-Type: application/json

{
    "title": "South Africa",
    "content": "South Africa is a country in Africa",
    "author": [
        {
        "fullName": "AB de Villiers",
        "email": "mr360@sa.com"
        }
   
    ]
}
###
POST http://localhost:8082/blogs/new
Content-Type: application/json

{
    "title": "Zimbabwe",
    "content": "Zimbabwe is a beautiful country.",
    "author": [
        {
        "fullName": "Andy Flower",
        "email": "andyf@zimc.com",
        "image": "https://www.google.com/andy.jpg" 
        }
   
    ]
}
###
POST http://localhost:8082/blogs/new
Content-Type: application/json

{
    "title": "Sri Lanka",
    "content": "Sri Lanka is a beautiful island.",
    "author": [
        {
        "fullName": "Kumar Sangakara",
        "email": "kumars@gmail.com",
        "image": "https://www.google.com/andy.jpg" 
        }
   
    ]
}

GET http://localhost:8082/blogs/search?title=India&author=Sachin